# Data Preparation Template

## This notebook is for Data Cleaning and Feature Engineering

## Data Tasks

### 1) Understand the shape of the data (Histograms, box plots, etc.)

### 2) Data Cleaning 

### 3) Data Exploration

### 4) Feature Engineering 

### 5) Data Preprocessing for Model

### 6) Basic Model Building 

### 7) Model Tuning 

### 8) Ensemble Model Building 

### 9) Results

## Import Libraries

In [1]:
import numpy as np
#from numpy import count_nonzero, median, mean
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import random
#import squarify

import datetime
from datetime import datetime, timedelta, date, time


#import os
#import zipfile
import scipy
from scipy import stats
#from scipy.stats.mstats import normaltest # D'Agostino K^2 Test
#from scipy.stats import boxcox
from collections import Counter

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, OneHotEncoder, OrdinalEncoder, LabelEncoder
from sklearn.preprocessing import PolynomialFeatures, RobustScaler, Binarizer
from sklearn.impute import SimpleImputer, MissingIndicator, KNNImputer
from sklearn.compose import make_column_transformer, ColumnTransformer
from sklearn.pipeline import make_pipeline, Pipeline
from sklearn import set_config

%matplotlib inline
#sets the default autosave frequency in seconds
%autosave 60 
sns.set_style('dark')
sns.set(font_scale=1.2)

plt.rc('axes', titlesize=9)
plt.rc('axes', labelsize=14)
plt.rc('xtick', labelsize=12)
plt.rc('ytick', labelsize=12)

import warnings
warnings.filterwarnings('ignore')

# Use Feature-Engine library
import feature_engine

from feature_engine.imputation import AddMissingIndicator, CategoricalImputer, DropMissingData, MeanMedianImputer
from feature_engine.imputation import ArbitraryNumberImputer, RandomSampleImputer

from feature_engine.outliers import Winsorizer, ArbitraryOutlierCapper, OutlierTrimmer

from feature_engine.encoding import CountFrequencyEncoder, DecisionTreeEncoder, MeanEncoder, OneHotEncoder
from feature_engine.encoding import OrdinalEncoder, WoEEncoder, RareLabelEncoder, StringSimilarityEncoder

from feature_engine.discretisation import EqualWidthDiscretiser, EqualFrequencyDiscretiser, ArbitraryDiscretiser
from feature_engine.discretisation import DecisionTreeDiscretiser, EqualWidthDiscretiser

from feature_engine.datetime import DatetimeFeatures

from feature_engine.creation import CyclicalFeatures, MathFeatures, RelativeFeatures


pd.set_option('display.max_columns',None)
#pd.set_option('display.max_rows',None)
pd.set_option('display.width', 1000)
pd.set_option('display.float_format','{:.2f}'.format)

random.seed(0)
np.random.seed(0)
np.set_printoptions(suppress=True)

Autosaving every 60 seconds

**==============================================================================**

## Data Quick Glance

In [2]:
df = pd.read_csv("survey_data.csv")

In [2]:
df = pd.read_csv("survey_data_updated 5.csv")

In [3]:
df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,2,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,20,17,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Bash/Shell (all shells);Go;HTML/CSS;Java;JavaS...,Dynamodb;MongoDB;PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Amazon Web Services (AWS);Heroku;Netlify,Express;Next.js;Node.js;React,Express;Htmx;Node.js;React;Remix,Express;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,Docker;Homebrew;Kubernetes;npm;Vite;Webpack,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,PyCharm;Visual Studio Code;WebStorm,MacOS;Windows,MacOS,NaN,NaN,NaN,Microsoft Teams;Slack,Slack,Slack,NaN,NaN,NaN,Stack Overflow for Teams (private knowledge sh...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Individual contributor,17.00,Agree,Disagree,Agree,Agree,Agree,Neither agree nor disagree,Disagree,Agree,Agree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN
1,3,I am a developer by profession,45-54 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Other...,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Blogs;Books;Written Tu...,API document(s) and/or SDK document(s);User gu...,37,27,Developer Experience,NaN,NaN,NaN,NaN,NaN,United Kingdom of Great Britain and Northern I...,NaN,NaN,C#,C#,C#,Firebase Realtime Database,Firebase Realtime Database,Firebase Realtime Database,Google Cloud,Google Cloud,Google Cloud,ASP.NET CORE,ASP.NET CORE,ASP.NET CORE,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,.NET (5+) ;.NET Framework (1.0 - 4.8);.NET MAUI,MSBuild,MSBuild,MSBuild,Visual Studio,Visual Studio,Visual Studio,Windows,Windows,NaN,NaN,NaN,Google Chat;Google Meet;Microsoft Teams;Zoom,Google Chat;Google Meet;Zoom,Google Chat;Google Meet;Zoom,NaN,NaN,NaN,Stack Overflow;Stack Exchange;Stack Overflow B...,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Finding reliabl...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
2,10,I am a developer by profession,35-44 years old,"Independent contractor, freelancer, or self-em...",Remote,Apples,Bootstrapping a business,"Master's degree (M.A., M.S., M.Eng., MBA, etc.)",On the job training;Other online resources (e....,Technical documentation;Blogs;Written Tutorial...,Traditional public search engine;AI-powered se...,15,11,"Developer, full-stack",NaN,NaN,NaN,NaN,NaN,Serbia,NaN,NaN,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,HTML/CSS;JavaScript;TypeScript,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,MongoDB;MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);Digital Ocean;Fireba...,Amazon Web Services (AWS);Digital Ocean;Fireba...,Amazon Web Services (AWS);Digital Ocean;Fireba...,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,Express;Next.js;Node.js;React,NaN,NaN,NaN,NaN,NaN,NaN,npm;Webpack,npm;Webpack,npm;Webpack,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,Windows,Jira,Jira,Jira,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,Discord;Google Meet;Skype;Slack,ChatGPT;Google Gemini,ChatGPT;Google Gemini,ChatGPT;Google Gemini,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions,"Yes, somewhat",Yes,Indifferent,Increase productivity;Speed up learning,Neither trust nor distrust,Bad at handling complex tasks,Search for answers,NaN,NaN,NaN,Search for answers,NaN,NaN,NaN,I'm not sure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN,NaN
3,11,"I used to be a developer by profession, but no...",35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Books;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,20,NaN,Project manager,NaN,NaN,NaN,NaN,NaN,United States of America,NaN,NaN,JavaScript;Python;Ruby,C#;Crystal;Java;JavaScript;Python;Ruby,JavaScript;Python;Ruby,Elasticsearch;MongoDB;PostgreSQL;SQLite,Elasticsearch;MongoDB;PostgreSQL;SQLite,Elasticsearch;MongoDB;PostgreSQL;SQLite,Amazon Web Services (AWS);Google Cloud,Google Cloud,Google Cloud,Node.js;React;Ruby on Rails,Django;Node.js;React;Ruby on Rails,Node.js;React;Ruby on Rails,NaN,NaN,NaN,NaN,NaN,NaN,Ansible;Docker;Kubernetes,Ansible;Docker;Kubernetes,Ansible;Docker;Kubernetes,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows,Confluence;GitHub Discussions;Jira;Smartsheet,Confluence;GitHub Discussions;Jira,Confluence;GitHub Discussions;Jira,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Microsoft Teams;Slack;Zoom,Discord;Google Meet;Microsoft Teams;Slack;Zoom,ChatGPT;GitHub Copilot;Google Gemini;Meta AI;V...,GitHub Copilot;Google Gemini;Visual Studio Int...,GitHub Copilot;Google Gemini;Visual Studio Int...,Stack Overflow for Teams (private knowledge sh...,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, definitely",Yes,Favorable,Increase productivity;Speed up learning;Improv...,Somewhat distrust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Project planning;Testing code;Generating conte...,Committing and reviewing code;Deployment and m...,NaN,NaN,Learning about a codebase;Writing code;Documen...,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don't trust the output or answers;AI tools lac...,Yes,Individual contributor,15.00,Strongly agree,Agree,Strongly agree,Agree,Agree,Strongly agree,Agree,Neither agree nor disagree,Neither agree nor disagree,3-5 times a week,6-10 times a week,6-10 times a week,30-60 minutes a day,60-120 minutes a day,Amount of technical debt;Number of software to...,DevOps function;Automated testing;Observabilit...,Cloud only (single or multi-cloud),Internal Developer portal,Healthcare,50.00,0.00,0.00,25.00,10.00,0.00,15.00,0.00,0.00,Appropriate in length,Easy,NaN,8.00
4,12,I am a developer by profession,45-54 years old,"Employed, full-time",In-person,Apples,Hobby;School or academic work,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,30,25,Developer Advocate,NaN,NaN,NaN,NaN,NaN,Poland,NaN,NaN,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Power...,C#;HTML/CSS;JavaScript;PowerShell;Rust;SQL;Typ...,C#;HTML/CSS;JavaScript;PowerShell;SQL;TypeScript,Microsoft Access;Microsoft SQL Server;PostgreS...,Microsoft SQL Server;PostgreSQL;SQLite,Microsoft SQL Server;PostgreSQL;SQLite,Cloudflare,Cloudflare,Cloudflare,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React,ASP.NET;ASP.NET CORE;Express;jQuery;Node.js;React,NaN,NaN,NaN,.NET (5+) ;.NET Framework (1.0 - 4.8);RabbitMQ...,.NET (5+) ;.NET Framework (1.0 - 4.8);RabbitMQ,.NET (5+) ;.NET Framework (1.0 - 4.8);RabbitMQ,Docker;npm;Webpack;Yarn,Docker;npm;Webpack;Yarn,Docker;npm;Webpack;Yarn,Android Studio;IntelliJ IDEA;Netbeans;Notepad+...,Notepad++;Visual Studio;Visual Studio Code,Notepad++;Visual Studio;Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),NaN,NaN,NaN,Microsoft Teams,Microsoft Teams,Microsoft Teams,NaN,NaN,NaN,Stack Overflow;Stack Exchange,Multiple times per day,Yes,Multiple times per day,Quickly finding code solutions;Engage with com...,"Yes, definitely","No, and I don't plan to",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18845 entries, 0 to 18844
Columns: 114 entries, ResponseId to JobSat
dtypes: float64(13), int64(1), object(100)
memory usage: 16.4+ MB

In [5]:
df.dtypes.value_counts()

object     100
float64     13
int64        1
Name: count, dtype: int64

In [6]:
# Descriptive Statistical Analysis
df.describe(include="all")

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
count,18845.00,18845,18845,18845,18839,18845,18845,18845,18808,15931,13874,18794,18069,18801,17970,17957,17506,17051,17332,18845,18025,13469.00,18845,18845,18845,18845,18845,18845,18845,18845,18845,18845,18845,18845,6902,5913,5781,14058,13069,12387,18206,17934,17798,18699,18546,18479,18701,18624,17219,16005,15653,18460,17659,17271,15868,14713,14546,18773,18675,18682,15306,18578,18650,18787,15396,12838,12971,12924,12531,11189,8778,5169,4377,9029,752,353,15369,14566,13708,17128,12312,12274.00,11919,11682,11709,11693,11640,11637,11595,11584,11556,11822,11817,11583,12018,11990,11791,11676,11989,12003,12026,12137.00,12163.00,12170.00,12185.00,12185.00,12191.00,12184.00,12187.00,12182.00,18325,18336,9550.00,12111.00
unique,NaN,5,8,60,3,1,107,8,358,5740,98,52,52,34,10,3,193,3,348,161,125,NaN,9343,9778,6191,5635,5453,3142,3809,3398,2091,7702,7277,4217,692,625,495,4661,5273,2910,9992,9399,7365,6413,5003,4131,1420,1196,3877,2607,1963,2741,1940,1637,1460,1359,927,32,5,3,6,98,6,3,6,98,5,5,887,1455,997,503,361,604,138,130,3,122,210,2,2,NaN,5,5,5,5,5,5,5,5,5,5,5,5,5,5,820,471,3,9,15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,3,NaN,NaN
top,NaN,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,"Bachelor's degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,10,3,"Developer, full-stack",20 to 99 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Reputation for quality and ...,United States of America,EUR European Euro,NaN,HTML/CSS;JavaScript;TypeScript,C#;HTML/CSS;JavaScript;SQL;TypeScript,HTML/CSS;JavaScript;TypeScript,PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS),Amazon Web Services (AWS),Amazon Web Services (AWS),Spring Boot,Spring Boot,Spring Boot,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8),.NET (5+),.NET (5+),Docker,Docker,Docker,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,MacOS,Jira,Jira,Jira,Microsoft Teams,Microsoft Teams,Microsoft Teams,ChatGPT,ChatGPT;GitHub Copilot,ChatGPT,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"No, not really",Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code,Learning about a codebase,Project planning,Search for answers,Writing code,Writing code,Writing code,Writing code,No,Circulating misinformation or disinformation;M...,Don't trust the output or answers;AI tools lac...,Yes,Individual contributor,NaN,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,15-30 minutes a day,None of these,None of these,Cloud only (single or multi-cloud),Traditional public search engine,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
freq,NaN,17139,7788,12664,8168,18845,2731,8629,935,190,2221,1560,1334,8666,3880,7341,2585,10617,629,3441,4554,NaN,291,230,421,994,1265,1996,2391,2362,3353,398,443,613,1650,1406,1653,917,1022,1656,225,274,412,1819,2280,2787,2926,3323,1010,1036,1165,1595,1590,1741,3001,2448,3373,9462,6120,15341,8378,4424,5237,13000,7458,1601,5252,4267,655,190,776,482,637,931,160,45,10916,1104,2103,12354,10323,NaN,5531,3791,4724,5361,6173,4217,4280,4755,3039,7115,5107,6162,4665,3793,938,931,5817,6542,5351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12358,9851,NaN,NaN
mean,28819.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,74244561585863837051678418948630104554780872581...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.62,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20.70,8.03,11.99,25.29,24.57,22.86,17.30,12.22,11.36,NaN,NaN,84589.70,7.15
std,17541.60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,86165283952343893564196624296542348271157308573...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26.96,19.11,23.50,27.50,27.69,27.15,25.90,24.36,23.11,NaN,NaN,117385.65,1.99
min,2.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,1.00,0.00
25%,13747.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,60800.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.00,0.00,5.00,5.00,0.00,0.00,0.00,0.00,NaN,NaN,32222.00,6.00
50%,27907.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,115000.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.00,0.00,0.00,20.00,15.00,15.00,10.00,0.00,0.00,NaN,NaN,65857.50,8.00
75%,43410.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,273840.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25.00,6.00,10.00,30.00,30.00,30.00,20.00,10.00,10.00,NaN,NaN,110000.00,8.00
max,65432.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10000000000000001090105172493085719645223478342...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,100.00,NaN,NaN,6340564.00,10.00

In [7]:
# Descriptive Statistical Analysis
df.describe(include=["int", "float"])

       ResponseId                                          CompTotal  WorkExp  JobSatPoints_1  JobSatPoints_4  JobSatPoints_5  JobSatPoints_6  JobSatPoints_7  JobSatPoints_8  JobSatPoints_9  JobSatPoints_10  JobSatPoints_11  ConvertedCompYearly   JobSat
count    18845.00                                           13469.00 12274.00        12137.00        12163.00        12170.00        12185.00        12185.00        12191.00        12184.00         12187.00         12182.00              9550.00 12111.00
mean     28819.21 74244561585863837051678418948630104554780872581...    11.62           20.70            8.03           11.99           25.29           24.57           22.86           17.30            12.22            11.36             84589.70     7.15
std      17541.60 86165283952343893564196624296542348271157308573...     8.84           26.96           19.11           23.50           27.50           27.69           27.15           25.90            24.36            23.11            117385.65     1.99
min          2.00                                               0.00     0.00            0.00            0.00            0.00            0.00            0.00            0.00            0.00             0.00             0.00                 1.00     0.00
25%      13747.00                                           60800.00     5.00            0.00            0.00            0.00            5.00            5.00            0.00            0.00             0.00             0.00             32222.00     6.00
50%      27907.00                                          115000.00    10.00           10.00            0.00            0.00           20.00           15.00           15.00           10.00             0.00             0.00             65857.50     8.00
75%      43410.00                                          273840.00    16.00           25.00            6.00           10.00           30.00           30.00           30.00           20.00            10.00            10.00            110000.00     8.00
max      65432.00 10000000000000001090105172493085719645223478342...    50.00          100.00          100.00          100.00          100.00          100.00          100.00          100.00           100.00           100.00           6340564.00    10.00

In [8]:
# Descriptive Statistical Analysis
df.describe(include="object")

,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,SurveyLength,SurveyEase
count,18845,18845,18845,18839,18845,18845,18845,18808,15931,13874,18794,18069,18801,17970,17957,17506,17051,17332,18845,18025,18845,18845,18845,18845,18845,18845,18845,18845,18845,18845,18845,18845,6902,5913,5781,14058,13069,12387,18206,17934,17798,18699,18546,18479,18701,18624,17219,16005,15653,18460,17659,17271,15868,14713,14546,18773,18675,18682,15306,18578,18650,18787,15396,12838,12971,12924,12531,11189,8778,5169,4377,9029,752,353,15369,14566,13708,17128,12312,11919,11682,11709,11693,11640,11637,11595,11584,11556,11822,11817,11583,12018,11990,11791,11676,11989,12003,12026,18325,18336
unique,5,8,60,3,1,107,8,358,5740,98,52,52,34,10,3,193,3,348,161,125,9343,9778,6191,5635,5453,3142,3809,3398,2091,7702,7277,4217,692,625,495,4661,5273,2910,9992,9399,7365,6413,5003,4131,1420,1196,3877,2607,1963,2741,1940,1637,1460,1359,927,32,5,3,6,98,6,3,6,98,5,5,887,1455,997,503,361,604,138,130,3,122,210,2,2,5,5,5,5,5,5,5,5,5,5,5,5,5,5,820,471,3,9,15,3,3
top,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby,"Bachelor's degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Written Tutorial...,API document(s) and/or SDK document(s);User gu...,10,3,"Developer, full-stack",20 to 99 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Reputation for quality and ...,United States of America,EUR European Euro,HTML/CSS;JavaScript;TypeScript,C#;HTML/CSS;JavaScript;SQL;TypeScript,HTML/CSS;JavaScript;TypeScript,PostgreSQL,PostgreSQL,PostgreSQL,Amazon Web Services (AWS),Amazon Web Services (AWS),Amazon Web Services (AWS),Spring Boot,Spring Boot,Spring Boot,Rasberry Pi,Rasberry Pi,Rasberry Pi,.NET (5+) ;.NET Framework (1.0 - 4.8),.NET (5+),.NET (5+),Docker,Docker,Docker,Visual Studio Code,Visual Studio Code,Visual Studio Code,Windows,MacOS,Jira,Jira,Jira,Microsoft Teams,Microsoft Teams,Microsoft Teams,ChatGPT,ChatGPT;GitHub Copilot,ChatGPT,Stack Overflow;Stack Exchange,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"No, not really",Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,"Good, but not great at handling complex tasks",Writing code,Learning about a codebase,Project planning,Search for answers,Writing code,Writing code,Writing code,Writing code,No,Circulating misinformation or disinformation;M...,Don't trust the output or answers;AI tools lac...,Yes,Individual contributor,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,Agree,1-2 times a week,1-2 times a week,1-2 times a week,30-60 minutes a day,15-30 minutes a day,None of these,None of these,Cloud only (single or multi-cloud),Traditional public search engine,Software Development,Appropriate in length,Easy
freq,17139,7788,12664,8168,18845,2731,8629,935,190,2221,1560,1334,8666,3880,7341,2585,10617,629,3441,4554,291,230,421,994,1265,1996,2391,2362,3353,398,443,613,1650,1406,1653,917,1022,1656,225,274,412,1819,2280,2787,2926,3323,1010,1036,1165,1595,1590,1741,3001,2448,3373,9462,6120,15341,8378,4424,5237,13000,7458,1601,5252,4267,655,190,776,482,637,931,160,45,10916,1104,2103,12354,10323,5531,3791,4724,5361,6173,4217,4280,4755,3039,7115,5107,6162,4665,3793,938,931,5817,6542,5351,12358,9851

In [9]:
df.columns

Index(['ResponseId', 'MainBranch', 'Age', 'Employment', 'RemoteWork', 'Check', 'CodingActivities', 'EdLevel', 'LearnCode', 'LearnCodeOnline',
       ...
       'JobSatPoints_6', 'JobSatPoints_7', 'JobSatPoints_8', 'JobSatPoints_9', 'JobSatPoints_10', 'JobSatPoints_11', 'SurveyLength', 'SurveyEase', 'ConvertedCompYearly', 'JobSat'], dtype='object', length=114)

In [10]:
df.isnull().sum()

ResponseId                0
MainBranch                0
Age                       0
Employment                0
RemoteWork                6
                       ...
JobSatPoints_11        6663
SurveyLength            520
SurveyEase              509
ConvertedCompYearly    9295
JobSat                 6734
Length: 114, dtype: int64

In [11]:
df.duplicated().sum()

0

In [12]:
sample_df = df.sample(n=1000, random_state=42)

In [13]:
sample_df.head()

,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
17138,54362,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Boots...,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Books;Stack Overflow;C...,API document(s) and/or SDK document(s);User gu...,16,15,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Out-of-the-box is ready to go with little need...,APIs;Customization;Quality support system;Repu...,France,EUR European Euro,60000.00,HTML/CSS;JavaScript;Objective-C;PHP;SQL;TypeSc...,HTML/CSS;JavaScript;PHP;SQL;TypeScript,HTML/CSS;JavaScript;PHP;SQL;TypeScript,Elasticsearch;MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);OVH;Scaleway,Amazon Web Services (AWS);Google Cloud;OVH,Amazon Web Services (AWS);OVH,Laravel;React;Symfony,Laravel;Symfony,Laravel;Symfony,Rasberry Pi,NaN,NaN,NaN,NaN,NaN,Composer;npm;Yarn,Composer;npm;Yarn,Composer;npm;Yarn,Nano;PhpStorm;Vim,Nano;PhpStorm;Vim,Nano;PhpStorm;Vim,Windows;Windows Subsystem for Linux (WSL),Ubuntu;Windows;Windows Subsystem for Linux (WSL),Jira,Jira,Jira,Google Meet;Slack;Zoom,Google Meet;Slack,Google Meet;Slack,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, somewhat","No, but I plan to soon",Unfavorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,Circulating misinformation or disinformation;B...,Don't trust the output or answers,Yes,Individual contributor,15.00,Agree,Agree,Disagree,Agree,Agree,Agree,Agree,Disagree,Disagree,Never,1-2 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Amount of technical debt;Tracking my work,None of these,Cloud only (single or multi-cloud),Slack search,Software Development,10.00,2.00,20.00,30.00,10.00,14.00,5.00,5.00,4.00,Too long,Neither easy nor difficult,NaN,8.00
423,1290,I am a developer by profession,55-64 years old,"Employed, full-time",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",On the job training;Other online resources (e....,Blogs;Written Tutorials;Coding sessions (live ...,NaN,30,17,"Developer, back-end",100 to 499 employees,I have little or no influence,Start a free trial;Visit developer communities...,Is set up to be customized and needs to be eng...,APIs;Customization;Integrated developer commun...,United States of America,USD\tUnited States dollar,150000.00,C#;SQL,C#;SQL,C#;SQL,Microsoft SQL Server,Microsoft SQL Server,Microsoft SQL Server,Cloudflare;Google Cloud;Microsoft Azure;VMware,Microsoft Azure,Microsoft Azure,ASP.NET;ASP.NET CORE;Blazor,ASP.NET CORE;Blazor,ASP.NET CORE;Blazor,NaN,NaN,NaN,.NET (5+),.NET (5+) ;.NET MAUI,.NET (5+),MSBuild;Visual Studio Solution,MSBuild;Visual Studio Solution,MSBuild;Visual Studio Solution,Notepad++;Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Windows,Windows,Confluence;GitHub Discussions;Jira,Azure Devops,NaN,Discord;Google Chat;Google Meet;Microsoft Team...,Discord;Microsoft Teams;Zoom,Discord;Microsoft Teams;Zoom,GitHub Copilot;Google Gemini;Meta AI;Visual St...,GitHub Copilot;Visual Studio Intellicode,GitHub Copilot;Visual Studio Intellicode,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Learning new-to...,"No, not at all",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Neither trust nor distrust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Committing and reviewing code;Deployment and m...,Project planning;Predictive analytics;Generati...,Documenting code;Debugging and getting help;Te...,NaN,Learning about a codebase;Writing code;Search ...,NaN,NaN,No,Circulating misinformation or disinformation;M...,Other (please specify):,Yes,Individual contributor,30.00,Agree,Agree,Disagree,Agree,Disagree,Agree,Strongly agree,Strongly disagree,Strongly agree,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Amount of technical debt;Number of software to...,None of these,Hybrid (on-prem and cloud),Traditional public search engine,Other:,5.00,0.00,5.00,25.00,20.00,15.00,5.00,15.00,10.00,Too long,Easy,150000.00,8.00
11434,34251,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,I don't code outside of work,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Colleague;On the job training;Other online res...,Blogs;Stack Overflow;Coding sessions (live or ...,NaN,11,10,"Developer, full-stack","10,000 or more employees",I have little or no influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,AI tool integration,India,INR\tIndian rupee,NaN,Go;HTML/CSS;Java;JavaScript;PowerShell;Rust;Ty...,Go;HTML/CSS;Java;JavaScript;PowerShell;Rust;Ty...,Go;HTML/CSS;Java;JavaScript;PowerShell;Rust;Ty...,Cassandra;MariaDB;MySQL,MariaDB;MySQL,MariaDB;MySQL,Microsoft Azure;OpenShift,Microsoft Azure;OpenShift,Microsoft Azure;OpenShift,Angular;AngularJS;Express;Node.js;React,Angular;Htmx;Next.js;Node.js;React;Solid.js;Vu...,Angular;Node.js;React,Cargo,Cargo,Cargo,NaN,NaN,NaN,Ansible;Chocolatey;Docker;Kubernetes;Maven (bu...,Bun;Kubernetes;Make;Maven (build tool);npm;Pod...,Kubernetes;Maven (build tool);npm;Vite;Yarn,IntelliJ IDEA;Notepad++;Visual Studio Code,IntelliJ IDEA;Notepad++;Visual Studio Code,IntelliJ IDEA;Notepad++;Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),Confluence,Confluence,Confluence,Microsoft Teams,Microsoft Teams,Microsoft Teams,Bing AI;ChatGPT;GitHub Copilot,Bing AI;ChatGPT;GitHub Copilot,Bing AI;ChatGPT;GitHub Copilot,Stack Overflow;Stack Overflow Blog or Podcast,A few times per week,Yes,A few times per month or weekly,Quickly finding code solutions;Finding reliabl...,Neutral,Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Committing a...,NaN,Writing code;Debugging and getting help;Testin...,NaN,Learning about a codebase,NaN,NaN,Yes,Circulating misinformation or disinformation;M...,Lack of proper training and education on new t...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
14783,45479,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Apples,Hobby;Freelance/contract work,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Written Tutorials;Vide...,API document(s) and/or SDK document(s);First-p...,8,4,"Developer, back-end",2 to 9 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Frequent updates to features,Germany,EUR European Euro,55000.00,C#;HTML/CSS;Java;JavaScript;Lua;PHP;TypeScript,C#;HTML/CSS;Java;JavaScript;Lua;PHP,C#;HTML/CSS;Java;JavaScript;Lua;PHP,MariaDB;MySQL;Redis;SQLite,MariaDB;MongoDB;MySQL;Redis;SQLite,MariaDB;MySQL;Redis;SQLite,Cloudflare;Hetzner,Cloudflare;Hetzner,Cloudflare;Hetzner,jQuery;Laravel;Next.js;React,Laravel,Laravel,Rasberry Pi,Arduino;Rasberry Pi,Rasberry Pi,.NET (5+),.NET (5+) ;TensorFlow,.NET (5+),Composer;Docker;npm;Unity 3D;Vite;Webpack,Composer;Docker;Unity 3D;Vite,Composer;Docker;Unity 3D;Vite,IntelliJ IDEA;Notepad++;PhpStorm;Rider,IntelliJ IDEA;Notepad++;PhpStorm;Rider,IntelliJ IDEA;Notepad++;PhpStorm;Rider,Android;Windows,MacOS;Ubuntu,NaN,NaN,NaN,Skype,NaN,NaN,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Finding reliabl...,"No, not at all",Yes,Favorable,Increase productivity,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Generating content or synthetic data,NaN,Learning about a codebase;Project planning;Doc...,NaN,Writing code;Generating content or synthetic data,NaN,NaN,NaN,No,Circulating misinformation or disinformation,Lack of proper training and education on new t...,Yes,Individual contributor,6.00,Disagree,Strongly disagree,Strongly disagree,Neither agree nor disagree,NaN,Disagree,Agree,Neither agree nor disagree,Disagree,1-2 times a week,6-10 times a week,Never,30-60 minutes a day,Over 120 minutes a day,Amount of technical debt,Continuous integration (CI) and (more often) c...,Cloud only (single or multi-cloud),Traditional public search engine,Software Development,0.00,0.00,5.00,20.00,40.00,25.00,0.00,10.00,0.00,Appropriate in length,Easy,NaN,9.00
5216,15265,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Books;Stack Over...,API document(s) and/or SDK document(s);User gu...,11,12,"Developer, full-stack",10 to 19 employees,I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Reputation for quality and excellence;Con...,Germany,EUR European Euro,90000.00,Elixir;Erlang;JavaScript;Ruby;Rust;TypeScript,Elixir;Erlang;Rust,Elixir;Erlang;Rust,PostgreSQL;Redis;SQLite;Supabase,PostgreSQL;SQLite;Supabase,PostgreSQL;SQLite;Supabase,Amazon Web Services (AWS);Fly.io;Hetzner,Fly.io;Hetzner,Fly.io;Hetzner,Phoenix;React;Ruby on Rails,Phoenix,Phoenix,Cargo;Rasberry Pi,Cargo;Rasberry Pi;SCons,Cargo;Rasberry Pi,Electron,Tauri,NaN,Docker;Kubernetes;Terraform;Vite,Docker;Kubernetes;Vite,Docker;Kubernetes;Vite,Neovim,Neovim,Neovim,Android;Debian;Other Linux-based;Ubuntu,Debian;Other Linux-based;Ubuntu,Jira;Miro;Obsidian,Linear;Obsidian,Obsidian,Discord;Signal;Slack,Signal;Slack,Signal;Slack,ChatGPT;Cody;GitHub Copilot,ChatGPT,ChatGPT,Stack Overflow;Stack Exchange;Stack Overflow B...,A few times per month or weekly,Yes,Less than once per month or monthly,Finding reliable guidance from community-vette...,Neutral,Yes,Very unfavorable,Increase productivity,Highly distrust,Very poor at handling complex tasks,Writing code,Learning about a codebase;Documenting code;Deb...,Project planning;Testing code;Deployment and m...,NaN,Writing code,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don't trust the output or answers;AI tools lac...,Yes,Individual contributor,11.00,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Disagree,Strongly disagree,NaN,Agree,1-2 times a week,1-2 times a week,1-2 times a week,Less than 15 minutes a day,Less than 15 minutes a day,Number of software tools in use;Complexity of ...,DevOps function;Automated testing;Observabilit...,Cloud only (single or multi-cloud),A coworker,Software Development,5.00,15.00,15.00,20.00,20.00,15.00,4.00,1.00,5.00,Appropriate in length,Easy,96666.00,7.00

In [14]:
sample_df.reset_index(inplace=True)

In [15]:
sample_df.head()

,index,ResponseId,MainBranch,Age,Employment,RemoteWork,Check,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,TechDoc,YearsCode,YearsCodePro,DevType,OrgSize,PurchaseInfluence,BuyNewTool,BuildvsBuy,TechEndorse,Country,Currency,CompTotal,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,PlatformHaveWorkedWith,PlatformWantToWorkWith,PlatformAdmired,WebframeHaveWorkedWith,WebframeWantToWorkWith,WebframeAdmired,EmbeddedHaveWorkedWith,EmbeddedWantToWorkWith,EmbeddedAdmired,MiscTechHaveWorkedWith,MiscTechWantToWorkWith,MiscTechAdmired,ToolsTechHaveWorkedWith,ToolsTechWantToWorkWith,ToolsTechAdmired,NEWCollabToolsHaveWorkedWith,NEWCollabToolsWantToWorkWith,NEWCollabToolsAdmired,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackSyncHaveWorkedWith,OfficeStackSyncWantToWorkWith,OfficeStackSyncAdmired,AISearchDevHaveWorkedWith,AISearchDevWantToWorkWith,AISearchDevAdmired,NEWSOSites,SOVisitFreq,SOAccount,SOPartFreq,SOHow,SOComm,AISelect,AISent,AIBen,AIAcc,AIComplex,AIToolCurrently Using,AIToolInterested in Using,AIToolNot interested in Using,AINextMuch more integrated,AINextNo change,AINextMore integrated,AINextLess integrated,AINextMuch less integrated,AIThreat,AIEthics,AIChallenges,TBranch,ICorPM,WorkExp,Knowledge_1,Knowledge_2,Knowledge_3,Knowledge_4,Knowledge_5,Knowledge_6,Knowledge_7,Knowledge_8,Knowledge_9,Frequency_1,Frequency_2,Frequency_3,TimeSearching,TimeAnswering,Frustration,ProfessionalTech,ProfessionalCloud,ProfessionalQuestion,Industry,JobSatPoints_1,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,SurveyLength,SurveyEase,ConvertedCompYearly,JobSat
0,17138,54362,I am a developer by profession,35-44 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects;Boots...,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Colleague;On the job tr...,Technical documentation;Books;Stack Overflow;C...,API document(s) and/or SDK document(s);User gu...,16,15,"Developer, full-stack","Just me - I am a freelancer, sole proprietor, ...",I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Out-of-the-box is ready to go with little need...,APIs;Customization;Quality support system;Repu...,France,EUR European Euro,60000.00,HTML/CSS;JavaScript;Objective-C;PHP;SQL;TypeSc...,HTML/CSS;JavaScript;PHP;SQL;TypeScript,HTML/CSS;JavaScript;PHP;SQL;TypeScript,Elasticsearch;MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,MySQL;PostgreSQL;Redis,Amazon Web Services (AWS);OVH;Scaleway,Amazon Web Services (AWS);Google Cloud;OVH,Amazon Web Services (AWS);OVH,Laravel;React;Symfony,Laravel;Symfony,Laravel;Symfony,Rasberry Pi,NaN,NaN,NaN,NaN,NaN,Composer;npm;Yarn,Composer;npm;Yarn,Composer;npm;Yarn,Nano;PhpStorm;Vim,Nano;PhpStorm;Vim,Nano;PhpStorm;Vim,Windows;Windows Subsystem for Linux (WSL),Ubuntu;Windows;Windows Subsystem for Linux (WSL),Jira,Jira,Jira,Google Meet;Slack;Zoom,Google Meet;Slack,Google Meet;Slack,NaN,NaN,NaN,Stack Overflow;Stack Exchange,A few times per month or weekly,Yes,Less than once per month or monthly,Quickly finding code solutions;Finding reliabl...,"Yes, somewhat","No, but I plan to soon",Unfavorable,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I'm not sure,Circulating misinformation or disinformation;B...,Don't trust the output or answers,Yes,Individual contributor,15.00,Agree,Agree,Disagree,Agree,Agree,Agree,Agree,Disagree,Disagree,Never,1-2 times a week,1-2 times a week,15-30 minutes a day,15-30 minutes a day,Amount of technical debt;Tracking my work,None of these,Cloud only (single or multi-cloud),Slack search,Software Development,10.00,2.00,20.00,30.00,10.00,14.00,5.00,5.00,4.00,Too long,Neither easy nor difficult,NaN,8.00
1,423,1290,I am a developer by profession,55-64 years old,"Employed, full-time",Remote,Apples,Hobby;Professional development or self-paced l...,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",On the job training;Other online resources (e....,Blogs;Written Tutorials;Coding sessions (live ...,NaN,30,17,"Developer, back-end",100 to 499 employees,I have little or no influence,Start a free trial;Visit developer communities...,Is set up to be customized and needs to be eng...,APIs;Customization;Integrated developer commun...,United States of America,USD\tUnited States dollar,150000.00,C#;SQL,C#;SQL,C#;SQL,Microsoft SQL Server,Microsoft SQL Server,Microsoft SQL Server,Cloudflare;Google Cloud;Microsoft Azure;VMware,Microsoft Azure,Microsoft Azure,ASP.NET;ASP.NET CORE;Blazor,ASP.NET CORE;Blazor,ASP.NET CORE;Blazor,NaN,NaN,NaN,.NET (5+),.NET (5+) ;.NET MAUI,.NET (5+),MSBuild;Visual Studio Solution,MSBuild;Visual Studio Solution,MSBuild;Visual Studio Solution,Notepad++;Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Visual Studio;Visual Studio Code,Windows,Windows,Confluence;GitHub Discussions;Jira,Azure Devops,NaN,Discord;Google Chat;Google Meet;Microsoft Team...,Discord;Microsoft Teams;Zoom,Discord;Microsoft Teams;Zoom,GitHub Copilot;Google Gemini;Meta AI;Visual St...,GitHub Copilot;Visual Studio Intellicode,GitHub Copilot;Visual Studio Intellicode,Stack Overflow,A few times per week,Yes,Less than once per month or monthly,Quickly finding code solutions;Learning new-to...,"No, not at all",Yes,Very favorable,Increase productivity;Greater efficiency;Impro...,Neither trust nor distrust,Neither good or bad at handling complex tasks,Learning about a codebase;Writing code;Documen...,Committing and reviewing code;Deployment and m...,Project planning;Predictive analytics;Generati...,Documenting code;Debugging and getting help;Te...,NaN,Learning about a codebase;Writing code;Search ...,NaN,NaN,No,Circulating misinformation or disinformation;M...,Other (please specify):,Yes,Individual contributor,30.00,Agree,Agree,Disagree,Agree,Disagree,Agree,Strongly agree,Strongly disagree,Strongly agree,1-2 times a week,1-2 times a week,3-5 times a week,60-120 minutes a day,30-60 minutes a day,Amount of technical debt;Number of software to...,None of these,Hybrid (on-prem and cloud),Traditional public search engine,Other:,5.00,0.00,5.00,25.00,20.00,15.00,5.00,15.00,10.00,Too long,Easy,150000.00,8.00
2,11434,34251,I am a developer by profession,25-34 years old,"Employed, full-time","Hybrid (some remote, some in-person)",Apples,I don't code outside of work,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Colleague;On the job training;Other online res...,Blogs;Stack Overflow;Coding sessions (live or ...,NaN,11,10,"Developer, full-stack","10,000 or more employees",I have little or no influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,AI tool integration,India,INR\tIndian rupee,NaN,Go;HTML/CSS;Java;JavaScript;PowerShell;Rust;Ty...,Go;HTML/CSS;Java;JavaScript;PowerShell;Rust;Ty...,Go;HTML/CSS;Java;JavaScript;PowerShell;Rust;Ty...,Cassandra;MariaDB;MySQL,MariaDB;MySQL,MariaDB;MySQL,Microsoft Azure;OpenShift,Microsoft Azure;OpenShift,Microsoft Azure;OpenShift,Angular;AngularJS;Express;Node.js;React,Angular;Htmx;Next.js;Node.js;React;Solid.js;Vu...,Angular;Node.js;React,Cargo,Cargo,Cargo,NaN,NaN,NaN,Ansible;Chocolatey;Docker;Kubernetes;Maven (bu...,Bun;Kubernetes;Make;Maven (build tool);npm;Pod...,Kubernetes;Maven (build tool);npm;Vite;Yarn,IntelliJ IDEA;Notepad++;Visual Studio Code,IntelliJ IDEA;Notepad++;Visual Studio Code,IntelliJ IDEA;Notepad++;Visual Studio Code,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),Confluence,Confluence,Confluence,Microsoft Teams,Microsoft Teams,Microsoft Teams,Bing AI;ChatGPT;GitHub Copilot,Bing AI;ChatGPT;GitHub Copilot,Bing AI;ChatGPT;GitHub Copilot,Stack Overflow;Stack Overflow Blog or Podcast,A few times per week,Yes,A few times per month or weekly,Quickly finding code solutions;Finding reliabl...,Neutral,Yes,Favorable,Increase productivity;Greater efficiency;Speed...,Somewhat trust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Committing a...,NaN,Writing code;Debugging and getting help;Testin...,NaN,Learning about a codebase,NaN,NaN,Yes,Circulating misinformation or disinformation;M...,Lack of proper training and education on new t...,No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,NaN,NaN
3,14783,45479,I am a developer by profession,25-34 years old,"Employed, full-time;Independent contractor, fr...",Remote,Apples,Hobby;Freelance/contract work,"Secondary school (e.g. American high school, G...",On the job training;Other online resources (e....,Technical documentation;Written Tutorials;Vide...,API document(s) and/or SDK document(s);First-p...,8,4,"Developer, back-end",2 to 9 employees,I have some influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Customization;Frequent updates to features,Germany,EUR European Euro,55000.00,C#;HTML/CSS;Java;JavaScript;Lua;PHP;TypeScript,C#;HTML/CSS;Java;JavaScript;Lua;PHP,C#;HTML/CSS;Java;JavaScript;Lua;PHP,MariaDB;MySQL;Redis;SQLite,MariaDB;MongoDB;MySQL;Redis;SQLite,MariaDB;MySQL;Redis;SQLite,Cloudflare;Hetzner,Cloudflare;Hetzner,Cloudflare;Hetzner,jQuery;Laravel;Next.js;React,Laravel,Laravel,Rasberry Pi,Arduino;Rasberry Pi,Rasberry Pi,.NET (5+),.NET (5+) ;TensorFlow,.NET (5+),Composer;Docker;npm;Unity 3D;Vite;Webpack,Composer;Docker;Unity 3D;Vite,Composer;Docker;Unity 3D;Vite,IntelliJ IDEA;Notepad++;PhpStorm;Rider,IntelliJ IDEA;Notepad++;PhpStorm;Rider,IntelliJ IDEA;Notepad++;PhpStorm;Rider,Android;Windows,MacOS;Ubuntu,NaN,NaN,NaN,Skype,NaN,NaN,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,ChatGPT;GitHub Copilot,Stack Overflow,Daily or almost daily,Yes,I have never participated in Q&A on Stack Over...,Quickly finding code solutions;Finding reliabl...,"No, not at all",Yes,Favorable,Increase productivity,Somewhat trust,"Good, but not great at handling complex tasks",Writing code;Generating content or synthetic data,NaN,Learning about a codebase;Project planning;Doc...,NaN,Writing code;Generating content or synthetic data,NaN,NaN,NaN,No,Circulating misinformation or disinformation,Lack of proper training and education on new t...,Yes,Individual contributor,6.00,Disagree,Strongly disagree,Strongly disagree,Neither agree nor disagree,NaN,Disagree,Agree,Neither agree nor disagree,Disagree,1-2 times a week,6-10 times a week,Never,30-60 minutes a day,Over 120 minutes a day,Amount of technical debt,Continuous integration (CI) and (more often) c...,Cloud only (single or multi-cloud),Traditional public search engine,Software Development,0.00,0.00,5.00,20.00,40.00,25.00,0.00,10.00,0.00,Appropriate in length,Easy,NaN,9.00
4,5216,15265,I am a developer by profession,25-34 years old,"Employed, full-time",Remote,Apples,Hobby;Contribute to open-source projects,"Bachelor's degree (B.A., B.S., B.Eng., etc.)",Books / Physical media;Other online resources ...,Technical documentation;Blogs;Books;Stack Over...,API document(s) and/or SDK document(s);User gu...,11,12,"Developer, full-stack",10 to 19 employees,I have a great deal of influence,Start a free trial;Ask developers I know/work ...,Is ready-to-go but also customizable for growt...,APIs;Reputation for quality and excellence;Con...,Germany,EUR European Euro,90000.00,Elixir;Erlang;JavaScript;Ruby;Rust;TypeScript,Elixir;Erlang;Rust,Elixir;Erlang;Rust,PostgreSQL;Redis;SQLite;Supabase,PostgreSQL;SQLite;Supabase,PostgreSQL;SQLite;Supabase,Amazon Web Services (AWS);Fly.io;Hetzner,Fly.io;Hetzner,Fly.io;Hetzner,Phoenix;React;Ruby on Rails,Phoenix,Phoenix,Cargo;Rasberry Pi,Cargo;Rasberry Pi;SCons,Cargo;Rasberry Pi,Electron,Tauri,NaN,Docker;Kubernetes;Terraform;Vite,Docker;Kubernetes;Vite,Docker;Kubernetes;Vite,Neovim,Neovim,Neovim,Android;Debian;Other Linux-based;Ubuntu,Debian;Other Linux-based;Ubuntu,Jira;Miro;Obsidian,Linear;Obsidian,Obsidian,Discord;Signal;Slack,Signal;Slack,Signal;Slack,ChatGPT;Cody;GitHub Copilot,ChatGPT,ChatGPT,Stack Overflow;Stack Exchange;Stack Overflow B...,A few times per month or weekly,Yes,Less than once per month or monthly,Finding reliable guidance from community-vette...,Neutral,Yes,Very unfavorable,Increase productivity,Highly distrust,Very poor at handling complex tasks,Writing code,Learning about a codebase;Documenting code;Deb...,Project planning;Testing code;Deployment and m...,NaN,Writing code,NaN,NaN,NaN,No,Circulating misinformation or disinformation;M...,Don't trust the output or answers;AI tools lac...,Yes,Individual contributor,11.00,Strongly agree,Neither agree nor disagree,Agree,Agree,Agree,Disagree,Strongly disagree,NaN,Agree,1-2 times a week,1-2 times a week,1-2 times a week,Less than 15 minutes a day,Less than 15 minutes a day,Number of software tools in use;Complexity of ...,DevOps function;Automated testing;Observabilit...,Cloud only (single or multi-cloud),A coworker,Software Development,5.00,15.00,15.00,20.00,20.00,15.00,4.00,1.00,5.00,Appropriate in length,Easy,96666.00,7.00

In [ ]:
#sample_df = df.sample(n=min(1000, len(df)), random_state=42)

In [ ]:
#sample_df = df.sample(frac=0.01, random_state=42)  # 1% of rows

In [ ]:
#sample_df = df.sample(n=1000, replace=True, random_state=42)

In [16]:
#sample_df.to_csv("survey_sample.csv", index=False)

In [16]:
#sample_df.to_csv("surveyupdated_sample.csv", index=False)

**=================================================================**